find("Login-1.png")
click("Login-1.png")
wait("LoginUsernam.png")
click(Pattern("Jsername.png").targetOffset(-92,11))
type("hanifnaufal")
type(Key.TAB)
type("dingdong57")
click("1419476002583.png")
assert exists("Logout.png")