find("Kategori.png")
click("Kategori.png")
t = find("Dix17Tester-1.png")
r = Region(t)
wait(3)
r.click("i.png")
click(Pattern("Namaester.png").targetOffset(-143,10))
wait(3)
type("a",KEY_CTRL)
type(Key.DELETE)
type(Key.ENTER)
assert exists("NamaNamacann.png")