find("Daftar-1.png")
click(Pattern("Daftar-1.png").targetOffset(-1,-1))
wait("DaftarUserna.png")
click(Pattern("UsernameNoSp.png").targetOffset(-97,15))
type("tester10")
type(Key.TAB)
type("tester10@lalala.com")
type(Key.TAB)
type("tester")
type(Key.TAB)
type("tester")
click("1419483392835.png")
assert exists("Emailtidakte.png")